name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platforms;android-34" "platform-tools" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper 8.7
        run: gradle wrapper --gradle-version 8.7

      - name: Ensure gradle.properties
        run: |
          cat > gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.nonTransitiveRClass=true
          EOF
          echo "gradle.properties content:"
          cat gradle.properties

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
